### ISSUE TITLE
In which file is the code for the radiance demodulation module?

### ISSUE THREAD

**Issue by xautstuzfy** [Riga2/NSRD#2]
Please help me

**Comment by Riga2** [comment]
We implemented the radiance demodulation strategy in the Unity Engine to generate the LR lighting components directly. 

You can refer to [Real Shading in Unreal Engine 4](https://cdn2-unrealengine-1251447533.file.myqcloud.com/Resources/files/2013SiggraphPresentationsNotes-26915738.pdf) and our paper/supplementary to implement the strategy.
