### ISSUE TITLE
Dataset only on Baidu

### ISSUE THREAD

**Issue by CharlieRusso001** [Riga2/NSRD#4]
Hello, I was very interested in this repo and I was trying to get the dataset but unfortunately I am not able to make a Baidu account to access the dataset provided is there any other way to get it?

thanks

**Comment by Riga2** [comment]
> Hello, I was very interested in this repo and I was trying to get the dataset but unfortunately I am not able to make a Baidu account to access the dataset provided is there any other way to get it?
> 
> thanks

Thanks for your interest in our work!
We will upload our dataset to OneDrive soon.

**Comment by Riga2** [comment]
> Hello, I was very interested in this repo and I was trying to get the dataset but unfortunately I am not able to make a Baidu account to access the dataset provided is there any other way to get it?
> 
> thanks

Three scenes are here: [Bitsro](https://mailsdueducn-my.sharepoint.com/:u:/g/personal/cuteloong_mail_sdu_edu_cn/EWaiWyZbRxNLgWw7wTV6IBYB2NXLimZ4JcvKhlWpZQ6Jzg?e=hc9scu), [Pica](https://mailsdueducn-my.sharepoint.com/:u:/g/personal/202215216_mail_sdu_edu_cn/ESRf0I6mKH1PqL9wpOW-q7YBYygrKDF9q13piFd1Xyce9g?e=sNhN72) and [San_M](https://mailsdueducn-my.sharepoint.com/:u:/g/personal/202215216_mail_sdu_edu_cn/Eek4usuLcUZGlHCnpzPD63YBukX5FlXELUbTzWa3_zsx1Q?e=nFAwRR).

**Comment by CharlieRusso001** [comment]
Ok thank you very much

**Comment by CharlieRusso001** [comment]
![IMG_5381](https://github.com/Riga2/NSRD/assets/158984051/0618a257-3f21-43d4-affc-84d4ca001fcb)
When opening the one drive I end up getting this error can you please make it public?

**Comment by Riga2** [comment]
> ![IMG_5381](https://private-user-images.githubusercontent.com/158984051/331476186-0618a257-3f21-43d4-affc-84d4ca001fcb.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU5MjYxMDQsIm5iZiI6MTcxNTkyNTgwNCwicGF0aCI6Ii8xNTg5ODQwNTEvMzMxNDc2MTg2LTA2MThhMjU3LTNmMjEtNDNkNC1hZmZjLTg0ZDRjYTAwMWZjYi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MTdUMDYwMzI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQ0NzdkNTQ4Zjk2OTUxNGYwMzVjODM0ZjM3NTYxY2VhMjBhNjM1MTQ1YjQ2ZGYyMTAwYTQzMzgyOWJiZGIyYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lulXQmNHXT9M8od-mxFuVYaIJy366q2DYH9JrP8aJE0) When opening the one drive I end up getting this error can you please make it public?

Sorry, we have updated the link of Bistro scene. You can try it again now.
