### ISSUE TITLE
what should I put for the "test_folder = ( )" in the Bistro_train.txt

### ISSUE THREAD

**Issue by ghost** [Riga2/NSRD#5]
Hi, I was trying to train the model and got this error below:
![error](https://github.com/Riga2/NSRD/assets/175045218/408ce560-3f0b-4dfc-85cc-978825c722a7)

I found that "test_folder = ( )" in the Bistro_train.txt. Could I know what I should put in the bracket so that I can train the model?
![Screenshop of ”Bistro_train txt“](https://github.com/Riga2/NSRD/assets/175045218/5d1f99a8-2c20-4496-8153-d5404ecf7779)

**Comment by Riga2** [comment]
Sorry for the late reply!

We have fixed some bugs for now. See [changes](https://github.com/Riga2/NSRD/commit/9243f93ffcbef079224ab5a9364bdbaefdd93f4d) here.

Hope it can help you!

**Comment by ghost** [comment]
Thanks for your reply and update.
